Hellenma Winter Units
SynixeContractors/Units pull request #1
Opened 2024-01-15 07:37 UTC by TWatson1162

2024-01-15 14:59 UTC, BrettMayson requested changes

2024-01-15 14:59 UTC, BrettMayson commented on addons/polkbaskera/CfgVehicles_Backpacks.hpp
> +		class TransportMagazines {RPG7_F,2};
```suggestion
		class TransportMagazines {
			class _xx_RPG7_F {
				magazine = "RPG7_F";
				count = 2;
			};
		};
```

2024-01-15 14:59 UTC, BrettMayson commented on addons/polkbaskera/CfgVehicles_Units.hpp
> +	Backpack = "B_AssaultPack_rgr_AT";
```suggestion
	Backpack = QCLASS(B_AssaultPack_rgr_AT);
```

2024-01-15 15:16 UTC, BrettMayson requested changes

2024-01-15 15:16 UTC, BrettMayson commented on addons/polkbaskera/CfgVehicles_Units.hpp
> +	Backpack = "B_AssaultPack_rgr_AT";
Use the backpack you've defined with the AT rounds
```suggestion
	backpack = QCLASS(B_AssaultPack_rgr_AT);
```

2024-01-15 15:16 UTC, BrettMayson commented on addons/polkbaskera/CfgVehicles_Units.hpp
> +	respawnMagazines[] = {R5("30Rnd_762x39_Mag_Green_F"), R3("RPG7_F"), R2("SmokeShell")};
Only need to add one, for the weapon
```suggestion
	magazines[] = {R5("30Rnd_762x39_Mag_Green_F"), "RPG7_F", R2("SmokeShell")};
	respawnMagazines[] = {R5("30Rnd_762x39_Mag_Green_F"), "RPG7_F", R2("SmokeShell")};
```

2024-01-15 15:16 UTC, BrettMayson commented on addons/polkbaskera/CfgVehicles_Backpacks.hpp
> +	class CLASS(B_AssaultPack_rgr_AT): B_AssaultPack_rgr {
```suggestion
	class CLASS(B_AssaultPack_rgr_AT): B_AssaultPack_rgr {
		dlc = QUOTE(PREFIX); 
		scope = 1; 
		scopeCurator = 1;
```

2024-01-16 05:09 UTC, TWatson1162 commented
ngl not sure what I did, but I did correctly apply all the changes requested -- however I tried to copy it for other roles (ex: CLS, Demo, Engi)

2024-01-16 05:10 UTC, TWatson1162 commented
yah that didn't work

2024-01-16 05:39 UTC, TWatson1162 commented
k last push of the night, no more stupid piecemeal updates

2024-02-07 08:15 UTC, merged